[package]
name = "worker"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = {version = "1.38.1", features = ["full"]}
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.120"
toml = "0.8.14"
actix-web = "4.8.0"

